name 'dhoppe-resolv'
version '0.0.2'

author 'Dennis Hoppe'
license 'GPLv2'
project_page 'http://github.com/dhoppe/puppet-resolv'
source 'git://github.com/dhoppe/puppet-resolv'
summary 'Resolv Module'
description 'Resolv Module for Debian, Ubuntu'
dependency 'dhoppe/puppet', '>=0.0.1'
